default:
  image: openjdk:21

stages:
  - build
  - test

build_app:
  stage: build
  script:
    - apt-get update && apt-get install -y make wget
    - wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
    - wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
    - make compile
  artifacts:
    paths:
      - bin/

test_app:
  stage: test
  needs:
    - build_app
  script:
    - apt-get update && apt-get install -y make
    - make test
